### ISSUE TITLE
Error Requiring in Electron Main Process

### ISSUE THREAD

**Issue by dougmolineux** [mmaelzer/mjpeg-consumer#14]
Hi there!

I have a simple electron app. I require mjpeg-consumer like this in the main process (process that spawns the BrowserWindow object):

```var MjpegConsumer = require("mjpeg-consumer");```

I'm running node v5.3.0 npm v3.3.12. I can `npm install mjpeg-consumer` with no issues:

> npm install mjpeg-consumer --save
> electron-test@1.0.0 /dev/electron-hello-world
> └── mjpeg-consumer@1.1.0 

But when I run the app I get this:

> Error: Cannot find module './build/Debug/buffertools.node'

If I comment out the require line (referenced above) the error goes away. Would you happen to know what could be causing this? Thank you very much!
Best regards,
Doug

**Comment by dougmolineux** [comment]
If this is more of an electron issue than a issue with this particular module, I can close this one and try to investigate that :)

**Comment by mmaelzer** [comment]
Hey Doug!

This appears to be an electron issue since the one mjpeg-consumer dependency, [buffertools](bnoordhuis/node-buffertools), is a native module.

I believe [this page](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md) provides the instructions you'll need to package mjpeg-consumer with an electron app. If you _still_ have issues, I may be be able to come up with a non-optimal way of implementing mjpeg-consumer without the use of buffertools, it'd just be a bit slower at processing images.

**Comment by dougmolineux** [comment]
Ah brilliant! Thank you Mike!

**Comment by mmaelzer** [comment]
My pleasure!
