### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cubecleveland** [mmaelzer/mjpeg-consumer#19]
Can i use the library to build a video of the frames?

**Comment by mmaelzer** [comment]
This library itself cannot create videos. However, since this library can emit JPEG images, you can [convert a series of JPEGs into a video via ffmpeg](http://ffmpeg.org/faq.html#How-do-I-encode-single-pictures-into-movies_003f). Something like [node-fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) might make this an easy process, but I have not looked into how easy/hard it would be to do the images to video conversion with node-fluent-ffmpeg.
